import type { Metadata } from "next";
import { Inter } from "next/font/google"
import { cn } from "@/lib/utils"
import "./globals.css";

const inter = Inter({ 
subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter' 
});
export const metadata: Metadata = {
  title: "Vioset",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("antialiased", "h-full", "dark", inter.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
